baseURL: https://12x.me
languageCode: en-us
defaultContentLanguage: en
theme: github.com/lxndrblz/anatole

title: Jason Lyu

enableEmoji: true
enableRobotsTXT: true

pygmentsUseClasses: true   
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

markup:
  goldmark:
    renderer:
      unsafe: true

disqusShortname: 12x

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

# Site parameters
params:
  title: JASON LYU
  author: xᴊᴀsᴏɴʟʏᴜ
  description: An open-source developer who codes for fun.
  profilePicture: https://avatars.githubusercontent.com/u/28824352
  favicon: https://avatars.githubusercontent.com/u/28824352?
  mainSections: home
  postSectionName: posts
  keywords: ''
  # copyright: '2020-{{ YEAR }} xᴊᴀsᴏɴʟʏᴜ'

  customCSS:
  customJS:

  math:
    enable: false
    use: katex

  socialIcons:
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:xjasonlyu@gmail.com
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/xjasonlyu
    - icon: fab fa-telegram
      title: Telegram
      url: https://t.me/xjasonlyu
    - icon: fab fa-twitter
      title: Twitter
      url: https://twitter.com/xjasonlyu

menu:
  main:
    - name: Home
      identifier: home
      weight: 100
      url: /
    - name: Posts
      weight: 200
      identifier: posts
      url: /posts/
    # - name: Links
    #   weight: 300
    #   identifier: links
    #   url: /links/
    - name: CV
      weight: 400
      identifier: cv
      url: /cv/
    - name: About
      weight: 500
      identifier: about
      url: /about/
  footer:
    # - name: anatole
    #   weight: 1
    #   identifier: anatole
    #   url: https://github.com/lxndrblz/anatole
    - name: Hugo
      weight: 2
      identifier: hugo
      url: https://gohugo.io/
