baseURL: https://12x.me
languageCode: en-us
defaultContentLanguage: en
theme: github.com/lxndrblz/anatole

title: Jason Lyu

enableEmoji: true
enableRobotsTXT: true

pygmentsUseClasses: true   
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

disqusShortname: 12x

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup
markup:
  highlight:
    anchorLineNos: true
    lineNos: false
    noClasses: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    renderer:
      unsafe: true

# Site parameters
params:
  title: Jason Lyu
  # title: Zhexuan (Jason) Lyu
  author: xᴊᴀsᴏɴʟʏᴜ
  description: An open-source developer who codes for fun.
  profilePicture: https://avatars.githubusercontent.com/u/28824352
  favicon: https://avatars.githubusercontent.com/u/28824352?
  mainSections: home
  postSectionName: posts
  # readMore: true
  keywords:
  # copyright: '2020-{{ YEAR }} xᴊᴀsᴏɴʟʏᴜ'

  # contentratio: 0.75

  doNotLoadAnimations: true
  enableMediumZoom: false

  # displayMode: light
  # disableThemeSwitcher: true
  # hidesidebar: true

  customCSS:
    - css/custom.css
  customJS:
    - js/custom.js

  math:
    enable: false
    use: katex

  socialIcons:
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:xjasonlyu@gmail.com
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/xjasonlyu
    - icon: fab fa-linkedin
      title: LinkedIn
      # url: https://www.linkedin.com/in/zhexuan-lyu/
      url: https://www.linkedin.com/
    - icon: fab fa-twitter
      title: Twitter
      url: https://twitter.com/xjasonlyu

menu:
  main:
    - name: Home
      identifier: home
      weight: 100
      url: /
    - name: Posts
      weight: 200
      identifier: posts
      url: /posts/
    # - name: LeetCode
    #   weight: 300
    #   identifier: leetcode
    #   url: https://leetcode.com/xjasonlyu
    - name: CV
      weight: 400
      identifier: cv
      url: /cv/
    - name: About
      weight: 500
      identifier: about
      url: /about/
  footer:
    - name: Anatole
      weight: 1
      identifier: anatole
      url: https://github.com/lxndrblz/anatole
    - name: Hugo
      weight: 2
      identifier: hugo
      url: https://gohugo.io/
